# Generated by Django 5.1 on 2024-08-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_educacion_experiencia_proyectos_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(upload_to='images/', verbose_name='Imagen'),
        ),
    ]
